name: Fetch data daily

on:
  schedule:
    - cron: "15 2 * * *"   # daily 02:15 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r data-pipeline/requirements.txt

      - name: Fetch data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python data-pipeline/fetch_data.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public-data/indicators.json
          git commit -m "data: update indicators [skip ci]" || echo "No changes"
          git push
